@Library('my_ocp_sharelib') _  
import com.aviro.OpenShiftHelper  

pipeline {
    //agent any  
    agent {
        label 'buildertwo'
    }
// oc login --token=sha256~xfssLZYgN179VUO7eaC1iJ1MfoUzd8LkG8F8c91IFKE --server=https://api.rm1.0a51.p1.openshiftapps.com:6443
    environment {
        OC_TOKEN = credentials('openshift_id')  // Jenkins credentials
        OC_SERVER = "https://api.rm1.0a51.p1.openshiftapps.com:6443"
        PROJECT = "lamr8-dev"
        IMAGE = "medlamin13956814/exercise"
        APP_NAME = "lamela2025"
        APP_DEPLOYMENT = "lamela2025-00001-deployment"
    }

    stages {
        stage('Login to OpenShift') {
            steps {
                script {
                    OpenShiftHelper.login(this, OC_TOKEN, OC_SERVER)
                }
            }
        }

        // stage('Deploy Application') {
        //     steps {
        //         script {
        //             OpenShiftHelper.deploy(this, PROJECT, IMAGE, APP_NAME)
        //         }
        //     }
        // }

        stage('Deploy Application') {
            steps {
                script {
                    OpenShiftHelper.deployDeployment(this, PROJECT, IMAGE, APP_NAME, APP_DEPLOYMENT)
                }
            }
        }

        stage('Check Deployment Status') {
            steps {
                script {
                    if (!OpenShiftHelper.checkDeployment(this, PROJECT, APP_NAME, APP_DEPLOYMENT)) {
                        error "Le déploiement a échoué !"
                    } else {
                        echo "L'application a été déployée avec succès sur OpenShift !"
                    }
                }
            }
        }
    }
}
